CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX form_submissions_pkey ON public.form_submissions USING btree (id);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX otp_codes_pkey ON public.otp_codes USING btree (id);
CREATE INDEX/CONSTRAINT: CREATE INDEX idx_otp_codes_email_code ON public.otp_codes USING btree (email, code);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX profiles_pkey ON public.profiles USING btree (id);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX profiles_user_id_key ON public.profiles USING btree (user_id);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX receipts_receipt_number_key ON public.receipts USING btree (receipt_number);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX receipts_pkey ON public.receipts USING btree (id);
CREATE INDEX/CONSTRAINT: CREATE INDEX idx_receipts_payment_date ON public.receipts USING btree (payment_date DESC);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX receipts_paypal_transaction_id_key ON public.receipts USING btree (paypal_transaction_id);
CREATE INDEX/CONSTRAINT: CREATE INDEX idx_receipts_user_id ON public.receipts USING btree (user_id);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX seo_blog_posts_slug_key ON public.seo_blog_posts USING btree (slug);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX seo_blog_posts_pkey ON public.seo_blog_posts USING btree (id);
CREATE INDEX/CONSTRAINT: CREATE INDEX seo_indexing_log_pinged_at_idx ON public.seo_indexing_log USING btree (pinged_at DESC);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX seo_indexing_log_pkey ON public.seo_indexing_log USING btree (id);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX seo_integrations_pkey ON public.seo_integrations USING btree (id);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX seo_integrations_provider_key ON public.seo_integrations USING btree (provider);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX seo_keyword_cache_pkey ON public.seo_keyword_cache USING btree (id);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX seo_page_overrides_pkey ON public.seo_page_overrides USING btree (id);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX seo_page_overrides_route_path_key ON public.seo_page_overrides USING btree (route_path);
CREATE INDEX/CONSTRAINT: CREATE INDEX seo_page_overrides_route_path_idx ON public.seo_page_overrides USING btree (route_path);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX seo_settings_pkey ON public.seo_settings USING btree (id);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX seo_tasks_pkey ON public.seo_tasks USING btree (id);
CREATE INDEX/CONSTRAINT: CREATE INDEX seo_tasks_scheduled_date_idx ON public.seo_tasks USING btree (scheduled_date);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX subscriptions_one_trial_per_user ON public.subscriptions USING btree (user_id) WHERE (plan_type = 'trial'::text);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX subscriptions_pkey ON public.subscriptions USING btree (id);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX user_roles_user_id_role_key ON public.user_roles USING btree (user_id, role);
CREATE INDEX/CONSTRAINT: CREATE UNIQUE INDEX user_roles_pkey ON public.user_roles USING btree (id);
